# Generated by Django 4.2.7 on 2023-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_subscriptionlevel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ben1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ben2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ben3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ben4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
